//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DougWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DougWebServiceReference.DougWebServiceSoap")]
    public interface DougWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name RandomNumberGeneratorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandomNumberGenerator", ReplyAction="*")]
        WebApplication.DougWebServiceReference.RandomNumberGeneratorResponse RandomNumberGenerator(WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandomNumberGenerator", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.RandomNumberGeneratorResponse> RandomNumberGeneratorAsync(WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HashString", ReplyAction="*")]
        WebApplication.DougWebServiceReference.HashStringResponse HashString(WebApplication.DougWebServiceReference.HashStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HashString", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.HashStringResponse> HashStringAsync(WebApplication.DougWebServiceReference.HashStringRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyHash", ReplyAction="*")]
        WebApplication.DougWebServiceReference.VerifyHashResponse VerifyHash(WebApplication.DougWebServiceReference.VerifyHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyHash", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.VerifyHashResponse> VerifyHashAsync(WebApplication.DougWebServiceReference.VerifyHashRequest request);
        
        // CODEGEN: Generating message contract since element name plainText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptString", ReplyAction="*")]
        WebApplication.DougWebServiceReference.EncryptStringResponse EncryptString(WebApplication.DougWebServiceReference.EncryptStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptString", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.EncryptStringResponse> EncryptStringAsync(WebApplication.DougWebServiceReference.EncryptStringRequest request);
        
        // CODEGEN: Generating message contract since element name cipherText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DecryptString", ReplyAction="*")]
        WebApplication.DougWebServiceReference.DecryptStringResponse DecryptString(WebApplication.DougWebServiceReference.DecryptStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DecryptString", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.DecryptStringResponse> DecryptStringAsync(WebApplication.DougWebServiceReference.DecryptStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandomNumberGeneratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandomNumberGenerator", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.RandomNumberGeneratorRequestBody Body;
        
        public RandomNumberGeneratorRequest() {
        }
        
        public RandomNumberGeneratorRequest(WebApplication.DougWebServiceReference.RandomNumberGeneratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandomNumberGeneratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int lowBound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int highBound;
        
        public RandomNumberGeneratorRequestBody() {
        }
        
        public RandomNumberGeneratorRequestBody(int lowBound, int highBound) {
            this.lowBound = lowBound;
            this.highBound = highBound;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandomNumberGeneratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandomNumberGeneratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.RandomNumberGeneratorResponseBody Body;
        
        public RandomNumberGeneratorResponse() {
        }
        
        public RandomNumberGeneratorResponse(WebApplication.DougWebServiceReference.RandomNumberGeneratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandomNumberGeneratorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RandomNumberGeneratorResult;
        
        public RandomNumberGeneratorResponseBody() {
        }
        
        public RandomNumberGeneratorResponseBody(string RandomNumberGeneratorResult) {
            this.RandomNumberGeneratorResult = RandomNumberGeneratorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashString", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.HashStringRequestBody Body;
        
        public HashStringRequest() {
        }
        
        public HashStringRequest(WebApplication.DougWebServiceReference.HashStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HashStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public HashStringRequestBody() {
        }
        
        public HashStringRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.HashStringResponseBody Body;
        
        public HashStringResponse() {
        }
        
        public HashStringResponse(WebApplication.DougWebServiceReference.HashStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HashStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HashStringResult;
        
        public HashStringResponseBody() {
        }
        
        public HashStringResponseBody(string HashStringResult) {
            this.HashStringResult = HashStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyHashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyHash", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.VerifyHashRequestBody Body;
        
        public VerifyHashRequest() {
        }
        
        public VerifyHashRequest(WebApplication.DougWebServiceReference.VerifyHashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyHashRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hash;
        
        public VerifyHashRequestBody() {
        }
        
        public VerifyHashRequestBody(string input, string hash) {
            this.input = input;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyHashResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.VerifyHashResponseBody Body;
        
        public VerifyHashResponse() {
        }
        
        public VerifyHashResponse(WebApplication.DougWebServiceReference.VerifyHashResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyHashResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyHashResult;
        
        public VerifyHashResponseBody() {
        }
        
        public VerifyHashResponseBody(bool VerifyHashResult) {
            this.VerifyHashResult = VerifyHashResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptString", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.EncryptStringRequestBody Body;
        
        public EncryptStringRequest() {
        }
        
        public EncryptStringRequest(WebApplication.DougWebServiceReference.EncryptStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string plainText;
        
        public EncryptStringRequestBody() {
        }
        
        public EncryptStringRequestBody(string plainText) {
            this.plainText = plainText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.EncryptStringResponseBody Body;
        
        public EncryptStringResponse() {
        }
        
        public EncryptStringResponse(WebApplication.DougWebServiceReference.EncryptStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncryptStringResult;
        
        public EncryptStringResponseBody() {
        }
        
        public EncryptStringResponseBody(string EncryptStringResult) {
            this.EncryptStringResult = EncryptStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptString", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.DecryptStringRequestBody Body;
        
        public DecryptStringRequest() {
        }
        
        public DecryptStringRequest(WebApplication.DougWebServiceReference.DecryptStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cipherText;
        
        public DecryptStringRequestBody() {
        }
        
        public DecryptStringRequestBody(string cipherText) {
            this.cipherText = cipherText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication.DougWebServiceReference.DecryptStringResponseBody Body;
        
        public DecryptStringResponse() {
        }
        
        public DecryptStringResponse(WebApplication.DougWebServiceReference.DecryptStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DecryptStringResult;
        
        public DecryptStringResponseBody() {
        }
        
        public DecryptStringResponseBody(string DecryptStringResult) {
            this.DecryptStringResult = DecryptStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DougWebServiceSoapChannel : WebApplication.DougWebServiceReference.DougWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DougWebServiceSoapClient : System.ServiceModel.ClientBase<WebApplication.DougWebServiceReference.DougWebServiceSoap>, WebApplication.DougWebServiceReference.DougWebServiceSoap {
        
        public DougWebServiceSoapClient() {
        }
        
        public DougWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DougWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DougWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DougWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.DougWebServiceReference.RandomNumberGeneratorResponse WebApplication.DougWebServiceReference.DougWebServiceSoap.RandomNumberGenerator(WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest request) {
            return base.Channel.RandomNumberGenerator(request);
        }
        
        public string RandomNumberGenerator(int lowBound, int highBound) {
            WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest inValue = new WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.RandomNumberGeneratorRequestBody();
            inValue.Body.lowBound = lowBound;
            inValue.Body.highBound = highBound;
            WebApplication.DougWebServiceReference.RandomNumberGeneratorResponse retVal = ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).RandomNumberGenerator(inValue);
            return retVal.Body.RandomNumberGeneratorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.RandomNumberGeneratorResponse> WebApplication.DougWebServiceReference.DougWebServiceSoap.RandomNumberGeneratorAsync(WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest request) {
            return base.Channel.RandomNumberGeneratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.RandomNumberGeneratorResponse> RandomNumberGeneratorAsync(int lowBound, int highBound) {
            WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest inValue = new WebApplication.DougWebServiceReference.RandomNumberGeneratorRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.RandomNumberGeneratorRequestBody();
            inValue.Body.lowBound = lowBound;
            inValue.Body.highBound = highBound;
            return ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).RandomNumberGeneratorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.DougWebServiceReference.HashStringResponse WebApplication.DougWebServiceReference.DougWebServiceSoap.HashString(WebApplication.DougWebServiceReference.HashStringRequest request) {
            return base.Channel.HashString(request);
        }
        
        public string HashString(string input) {
            WebApplication.DougWebServiceReference.HashStringRequest inValue = new WebApplication.DougWebServiceReference.HashStringRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.HashStringRequestBody();
            inValue.Body.input = input;
            WebApplication.DougWebServiceReference.HashStringResponse retVal = ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).HashString(inValue);
            return retVal.Body.HashStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.HashStringResponse> WebApplication.DougWebServiceReference.DougWebServiceSoap.HashStringAsync(WebApplication.DougWebServiceReference.HashStringRequest request) {
            return base.Channel.HashStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.HashStringResponse> HashStringAsync(string input) {
            WebApplication.DougWebServiceReference.HashStringRequest inValue = new WebApplication.DougWebServiceReference.HashStringRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.HashStringRequestBody();
            inValue.Body.input = input;
            return ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).HashStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.DougWebServiceReference.VerifyHashResponse WebApplication.DougWebServiceReference.DougWebServiceSoap.VerifyHash(WebApplication.DougWebServiceReference.VerifyHashRequest request) {
            return base.Channel.VerifyHash(request);
        }
        
        public bool VerifyHash(string input, string hash) {
            WebApplication.DougWebServiceReference.VerifyHashRequest inValue = new WebApplication.DougWebServiceReference.VerifyHashRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.VerifyHashRequestBody();
            inValue.Body.input = input;
            inValue.Body.hash = hash;
            WebApplication.DougWebServiceReference.VerifyHashResponse retVal = ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).VerifyHash(inValue);
            return retVal.Body.VerifyHashResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.VerifyHashResponse> WebApplication.DougWebServiceReference.DougWebServiceSoap.VerifyHashAsync(WebApplication.DougWebServiceReference.VerifyHashRequest request) {
            return base.Channel.VerifyHashAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.VerifyHashResponse> VerifyHashAsync(string input, string hash) {
            WebApplication.DougWebServiceReference.VerifyHashRequest inValue = new WebApplication.DougWebServiceReference.VerifyHashRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.VerifyHashRequestBody();
            inValue.Body.input = input;
            inValue.Body.hash = hash;
            return ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).VerifyHashAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.DougWebServiceReference.EncryptStringResponse WebApplication.DougWebServiceReference.DougWebServiceSoap.EncryptString(WebApplication.DougWebServiceReference.EncryptStringRequest request) {
            return base.Channel.EncryptString(request);
        }
        
        public string EncryptString(string plainText) {
            WebApplication.DougWebServiceReference.EncryptStringRequest inValue = new WebApplication.DougWebServiceReference.EncryptStringRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.EncryptStringRequestBody();
            inValue.Body.plainText = plainText;
            WebApplication.DougWebServiceReference.EncryptStringResponse retVal = ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).EncryptString(inValue);
            return retVal.Body.EncryptStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.EncryptStringResponse> WebApplication.DougWebServiceReference.DougWebServiceSoap.EncryptStringAsync(WebApplication.DougWebServiceReference.EncryptStringRequest request) {
            return base.Channel.EncryptStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.EncryptStringResponse> EncryptStringAsync(string plainText) {
            WebApplication.DougWebServiceReference.EncryptStringRequest inValue = new WebApplication.DougWebServiceReference.EncryptStringRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.EncryptStringRequestBody();
            inValue.Body.plainText = plainText;
            return ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).EncryptStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.DougWebServiceReference.DecryptStringResponse WebApplication.DougWebServiceReference.DougWebServiceSoap.DecryptString(WebApplication.DougWebServiceReference.DecryptStringRequest request) {
            return base.Channel.DecryptString(request);
        }
        
        public string DecryptString(string cipherText) {
            WebApplication.DougWebServiceReference.DecryptStringRequest inValue = new WebApplication.DougWebServiceReference.DecryptStringRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.DecryptStringRequestBody();
            inValue.Body.cipherText = cipherText;
            WebApplication.DougWebServiceReference.DecryptStringResponse retVal = ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).DecryptString(inValue);
            return retVal.Body.DecryptStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.DecryptStringResponse> WebApplication.DougWebServiceReference.DougWebServiceSoap.DecryptStringAsync(WebApplication.DougWebServiceReference.DecryptStringRequest request) {
            return base.Channel.DecryptStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.DougWebServiceReference.DecryptStringResponse> DecryptStringAsync(string cipherText) {
            WebApplication.DougWebServiceReference.DecryptStringRequest inValue = new WebApplication.DougWebServiceReference.DecryptStringRequest();
            inValue.Body = new WebApplication.DougWebServiceReference.DecryptStringRequestBody();
            inValue.Body.cipherText = cipherText;
            return ((WebApplication.DougWebServiceReference.DougWebServiceSoap)(this)).DecryptStringAsync(inValue);
        }
    }
}
